[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[mounts]]
# Mount a persistent volume for video uploads
mountPath = "/data"
